ALTER TABLE ROOM_BILLING
ADD (
    CONSTRAINT fk_room_billing_transaction FOREIGN KEY (TransactionID) REFERENCES TRANSACTION(TransactionID),
    CONSTRAINT fk_room_billing_room FOREIGN KEY (RoomID) REFERENCES ROOM(RoomID) ON DELETE CASCADE
);

ALTER TABLE MENU_BILLING
ADD (
    CONSTRAINT fk_menu_billing_transaction FOREIGN KEY (TransactionID) REFERENCES TRANSACTION(TransactionID),
    CONSTRAINT fk_menu_billing_menu FOREIGN KEY (MenuID) REFERENCES MENU(MenuID) ON DELETE CASCADE
);

ALTER TABLE STUDENT_TRANSACTION
ADD(
    CONSTRAINT FK_ST_Transaction FOREIGN KEY (TransactionID) REFERENCES Transaction(TransactionID) ON DELETE CASCADE,
    CONSTRAINT FK_ST_Student FOREIGN KEY (StudentID) REFERENCES Student(StudentID)
);

ALTER TABLE STAFF_TRANSACTION
ADD(
    CONSTRAINT fk_staff_transaction FOREIGN KEY (TransactionID) REFERENCES TRANSACTION(TransactionID),
    CONSTRAINT fk_staff_staff  FOREIGN KEY(StaffId) REFERENCES STAFF(StaffID) ON DELETE CASCADE
);


-- TASK and TASK_STAFF foreign keys

ALTER TABLE TASK
ADD CONSTRAINT fk_task_room FOREIGN KEY (RoomID) REFERENCES Room(RoomID) ON DELETE CASCADE


ALTER TABLE TASK_STAFF
    ADD(
        CONSTRAINT fk_ts_task FOREIGN KEY (TaskID) REFERENCES TASK(TaskID) ON DELETE CASCADE,
        CONSTRAINT fk_ts_staff FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID) ON DELETE CASCADE
);


-- Student_PhoneNumber multi value attribute relation

ALTER TABLE Student_PhoneNumber
ADD CONSTRAINT fk_student FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID);
