ALTER TABLE TRANSACTION
ADD CONSTRAINT transaction_pk PRIMARY KEY(TransactionID);

ALTER TABLE ROOM_BILLING
ADD CONSTRAINT pk_room_billing PRIMARY KEY(TransactionID);

ALTER TABLE MENU_BILLING
ADD CONSTRAINT pk_menu_billing PRIMARY KEY(TransactionID);

ALTER TABLE STAFF_TRANSACTION 
ADD CONSTRAINT pk_staff_transaction PRIMARY KEY (TransactionID);

ALTER TABLE STUDENT_TRANSACTION 
ADD CONSTRAINT pk_student_transaction PRIMARY KEY (TransactionID);

ALTER TABLE ROOM_ASSIGNMENT
ADD CONSTRAINT pk_room_assignment PRIMARY KEY (StudentID, AssignmentDate);

ALTER TABLE STUDENT_BILLING
ADD CONSTRAINT pk_student_billing PRIMARY KEY (TransactionID);

-- Primary Keys for STAFF and TASK Tables

ALTER TABLE STAFF 
ADD CONSTRAINT staff_pk PRIMARY KEY(StaffID);

ALTER TABLE TASK_STAFF 
ADD CONSTRAINT pk_task_staff PRIMARY KEY (TaskID, StaffID);

ALTER TABLE TASK 
ADD CONSTRAINT task_pk PRIMARY KEY(TaskID);

-- Primary Keys for STUDENT and ROOM Tables,

ALTER TABLE STUDENT 
ADD CONSTRAINT pk_student PRIMARY KEY(StudentID);

ALTER TABLE ROOM
ADD CONSTRAINT pk_room PRIMARY KEY (RoomID);


-- Student_PhoneNumber multi value attribute

ALTER TABLE Student_PhoneNumber
ADD CONSTRAINT pk_student_phone PRIMARY KEY (StudentID, PhoneNumber);

-- Unique Constraints for SUPPLY Table and MENU_SUPPLY, TASK_SUPPLY Relationships
ALTER TABLE SUPPLY
ADD CONSTRAINT pk_supply PRIMARY KEY (SupplyID);

ALTER TABLE MENU_SUPPLY
ADD CONSTRAINT pk_menu_supply PRIMARY KEY (MenuID, SupplyID);

ALTER TABLE TASK_SUPPLY
ADD CONSTRAINT pk_task_supply PRIMARY KEY (TaskID, SupplyID);
