ALTER TABLE TRANSACTION
ADD CONSTRAINT transaction_pk PRIMARY KEY(TransactionID)

ALTER TABLE ROOM_BILLING
ADD CONSTRAINT pk_room_billing PRIMARY KEY(TransactionID)

ALTER TABLE MENU_BILLING
ADD CONSTRAINT pk_menu_billing PRIMARY KEY(TransactionID)

ALTER TABLE STAFF_TRANSACTION 
ADD CONSTRAINT pk_staff_transaction PRIMARY KEY (TransactionID);