ALTER TABLE TRANSACTION
ADD CONSTRAINT transaction_pk PRIMARY KEY(TransactionID)

ALTER TABLE ROOM_BILLING
ADD CONSTRAINT pk_room_billing PRIMARY KEY(TransactionID)

ALTER TABLE MENU_BILLING
ADD CONSTRAINT pk_menu_billing PRIMARY KEY(TransactionID)

ALTER TABLE STAFF_TRANSACTION 
ADD CONSTRAINT pk_staff_transaction PRIMARY KEY (TransactionID);

ALTER TABLE STUDENT_TRANSACTION 
ADD CONSTRAINT pk_student_transaction PRIMARY KEY (TransactionID);

ALTER TABLE ROOM_ASSIGNMENT
ADD CONSTRAINT pk_room_assignment PRIMARY KEY (StudentID, AssignmentDate);

-- Primary Keys for STAFF and TASK Tables

ALTER TABLE STAFF 
ADD CONSTRAINT staff_pk PRIMARY KEY(StaffID);

ALTER TABLE TASK_STAFF 
ADD CONSTRAINT pk_task_staff PRIMARY KEY (TaskID, StaffID)

ALTER TABLE TASK 
ADD CONSTRAINT task_pk PRIMARY KEY(TaskID);

-- Primary Keys for STUDENT and ROOM Tables,

ALTER TABLE STUDENT 
ADD CONSTRAINT pk_student PRIMARY KEY(StudentID);

ALTER TABLE ROOM
ADD CONSTRAINT pk_room PRIMARY KEY (RoomID);


-- Student_PhoneNumber multi value attribute

ALTER TABLE Student_PhoneNumber
ADD CONSTRAINT pk_student_phone PRIMARY KEY (StudentID, PhoneNumber);
